"""Telegram workflow states (PRD §21)."""

from __future__ import annotations

from enum import Enum


class State(str, Enum):
    IDLE = "IDLE"
    WAITING_MATERIAL = "WAITING_MATERIAL"
    PROCESSING_MATERIAL = "PROCESSING_MATERIAL"

    # Theme confirmation is a real gate.
    WAITING_THEME_CONFIRMATION = "WAITING_THEME_CONFIRMATION"
    WAITING_THEME_EDIT = "WAITING_THEME_EDIT"

    WAITING_ARCHIVE = "WAITING_ARCHIVE"
    WAITING_ARCHIVE_NUMBER = "WAITING_ARCHIVE"  # alias

    WAITING_DATE = "WAITING_DATE"
    WAITING_LOCATION = "WAITING_LOCATION"
    WAITING_TRAINER = "WAITING_TRAINER"
    WAITING_SHIFT_GROUP = "WAITING_SHIFT_GROUP"
    WAITING_PERSONNEL_COUNT = "WAITING_PERSONNEL_COUNT"
    DATA_REVIEW = "DATA_REVIEW"
    GENERATING_QUESTIONS = "GENERATING_QUESTIONS"

    # QuestionSet preview gate: the bot waits for an explicit confirmation and
    # the QuestionSet is frozen for the rest of the session.
    WAITING_QUESTION_CONFIRMATION = "WAITING_QUESTION_CONFIRMATION"
    QUESTION_CONFIRMED = "QUESTION_CONFIRMED"

    PHOTO_UPLOAD = "PHOTO_UPLOAD"
    GENERATING_DOCUMENT = "GENERATING_DOCUMENT"
    VALIDATING_DOCUMENT = "VALIDATING_DOCUMENT"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"
